model_path:
  small: './models/Nemotron-Mini-4B-Instruct-Q8_0.gguf'
  large: './models/mistral-7b-instruct-v0.1.Q5_K_M.gguf'

model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: 
  'max_new_tokens': 512
  'temperature' : 0
  'context_length': 4096
  'gpu_layers' : 0

chat_history_path: "./chat_sessions/"

# Google API configuration
google_api_key: "AIzaSyBdabmndutVeyIRcTawr6ZySQBP3I7ozkM"
custom_search_engine_id: "c2e281dbb5a17498c"
